---
kind: pipeline
type: docker
name: studio

steps:
  - name: build
    image: harbor.online.njtech.edu.cn/drone/docker:latest
    settings:
      dockerfile: Dockerfile
      tag:
        - latest
        - ${DRONE_BUILD_NUMBER}
      registry: https://harbor.online.njtech.edu.cn
      repo: harbor.online.njtech.edu.cn/library/studio

image_pull_secrets:
  - dockerconfig
